CANDIDATE_TYPE_FRESHER = 'FRESHER'
CANDIDATE_TYPE_EXPERIENCED = 'EXPERIENCED'

QUALIFICATION_TYPE_BSC = 'BSC'
QUALIFICATION_TYPE_MSC = 'MSC'
QUALIFICATION_TYPE_BTECH = 'BTECH'
QUALIFICATION_TYPE_MTECH = 'MTECH'
QUALIFICATION_TYPE_BCA = 'BCA'
QUALIFICATION_TYPE_MCA = 'MCA'

ONE_YEAR = '1'
TWO_YEAR = '2'
THREE_YEAR = '3'
FOUR_YEAR = '4'
FIVE_YEAR = '5'
ABOVE_FIVE = '5+'

CANDIDATE_TYPE = (
    (CANDIDATE_TYPE_FRESHER, CANDIDATE_TYPE_FRESHER),
    (CANDIDATE_TYPE_EXPERIENCED, CANDIDATE_TYPE_EXPERIENCED),
    )

QUALIFICATION_TYPE = (
    (QUALIFICATION_TYPE_BSC, QUALIFICATION_TYPE_BSC),
    (QUALIFICATION_TYPE_MSC, QUALIFICATION_TYPE_MSC),
    (QUALIFICATION_TYPE_BTECH, QUALIFICATION_TYPE_BTECH),
    (QUALIFICATION_TYPE_MTECH, QUALIFICATION_TYPE_MTECH),
    (QUALIFICATION_TYPE_BCA, QUALIFICATION_TYPE_BCA),
    (QUALIFICATION_TYPE_MCA, QUALIFICATION_TYPE_MCA),
    )

EXPERIENCE_TYPE = (
    (ONE_YEAR, ONE_YEAR),
    (TWO_YEAR, TWO_YEAR),
    (THREE_YEAR, THREE_YEAR),
    (FOUR_YEAR, FOUR_YEAR),
    (FIVE_YEAR, FIVE_YEAR),
    (ABOVE_FIVE, ABOVE_FIVE),
    )