CANDIDATE_TYPE_FRESHER = 'FRESHER'
CANDIDATE_TYPE_EXPERIENCED = 'EXPERIENCED'


QUALIFICATION_TYPE_BSC = 'BSC'
QUALIFICATION_TYPE_MSC = 'MSC'
QUALIFICATION_TYPE_BTECH = 'BTECH'
QUALIFICATION_TYPE_MTECH = 'MTECH'
QUALIFICATION_TYPE_BCA = 'BCA'
QUALIFICATION_TYPE_MCA = 'MCA'

CANDIDATE_TYPE = (
    (CANDIDATE_TYPE_FRESHER, CANDIDATE_TYPE_FRESHER),
    (CANDIDATE_TYPE_EXPERIENCED, CANDIDATE_TYPE_EXPERIENCED),
    )

QUALIFICATION_TYPE = (
    (QUALIFICATION_TYPE_BSC, QUALIFICATION_TYPE_BSC),
    (QUALIFICATION_TYPE_MSC, QUALIFICATION_TYPE_MSC),
    (QUALIFICATION_TYPE_BTECH, QUALIFICATION_TYPE_BTECH),
    (QUALIFICATION_TYPE_MTECH, QUALIFICATION_TYPE_MTECH),
    (QUALIFICATION_TYPE_BCA, QUALIFICATION_TYPE_BCA),
    (QUALIFICATION_TYPE_MCA, QUALIFICATION_TYPE_MCA),
    )
